project:
  type: website
  output-dir: docs

website:
  title: "TestBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme: 
      light: sandstone
      dark: slate
    css: styles.css



